

--- #################### 数据库相关配置 ####################

spring:
  # 数据源配置项
  datasource:
    dynamic: # 多数据源配置
      primary: baby_time
      datasource:
        baby_time:
          url: jdbc:mysql://blk-mysql-local.com:63306/baby_time?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: blk@2024~NIUBI!mysql%mmm
        baby_time_log:
          url: jdbc:mysql://blk-mysql-local.com:63306/baby_time_log?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: blk@2024~NIUBI!mysql%mmm
        baby_time_statistics:
          url: jdbc:mysql://blk-mysql-local.com:63306/baby_time_statistics?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: blk@2024~NIUBI!mysql%mmm
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  data:
    redis:
      host: blk-redis.com # 地址
      port: 61379 # 端口
      database: 2 # 数据库索引
      password: "blk@2024~NIUBI!redis%h"
      username: default
      # 密码，建议生产环境开启


musk:
  auth:
    default-avatar-url: 'http://www.baidu.image.com'
  plugin:
    service:
      dynamic-source:
        ds:
          properties:
            auth:
              member: baby_time
              log: baby_time_log
              statistics: baby_time_statistics
            plugin:
              upload: baby_time_statistics

business:
  image:
    uploadImagePath: 'C:\tmp\static\image'
